name: build flannel

on: pull_request

env:
  GO_VERSION: "1.23"
  LINUX_ARCHES: "amd64 arm arm64 s390x ppc64le riscv64"
  REPOSITORY: flannel/flannel

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: set tag 
        run: echo "GIT_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Set up Go 1.x
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b #v5.4.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: go mod vendor
        run: go mod vendor

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 #v5.7.0
        with:
          images: ${{ env.REPOSITORY }}
          flavor: latest=false
          tags: |
            type=ref, event=branch

      - name: Build multi-arch Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 #v6.15.0
        with:
          context: .
          file: images/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64,linux/arm,linux/s390x,linux/ppc64le,linux/riscv64
          tags: ${{ steps.meta.outputs.tags }}
          build-args: TAG=${{ env.GIT_TAG }}

      - name: build for windows
        run: make dist/flanneld.exe
  
  